CACHE:
    MEMORY_JANITOR_INTERVAL: 1m
Database:
    Cache: "false"
    ConnMaxLifTime: 1h
    Database: ""
    Debug: "3"
    Enabled: "false"
    MaxIdleConns: "10"
    MaxOpenConns: "100"
    Params: ""
    Password: ""
    SSLMode: "false"
    Server: 127.0.0.1:3306
    SlowQueryThreshold: 500ms
    Type: sqlite
    Username: root
HTTP:
    BodyLimit: 128kb
    CaseSensitive: "false"
    CompressedFileSuffix: .evo.gz
    Concurrency: "1024"
    DisableDefaultContentType: "false"
    DisableDefaultDate: "false"
    DisableHeaderNormalizing: "false"
    DisableKeepalive: "false"
    ETag: "false"
    GETOnly: "false"
    Host: 0.0.0.0
    IdleTimeout: "0"
    Immutable: false
    Network: tcp4
    Port: "8081"
    Prefork: "false"
    ProxyHeader: X-Forwarded-For
    ReadBufferSize: 8kb
    ReadTimeout: 1s
    ReduceMemoryUsage: "false"
    ServerHeader: EVO NG
    StrictRouting: "false"
    UnescapePath: "false"
    WriteBufferSize: 4kb
    WriteTimeout: 5s
